name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # branch to deploy from

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build your site here if needed
      # - name: Build the site
      #   run: npm run build # Use your actual build command

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./dist # Replace with the output directory of your build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
